### ISSUE TITLE
Persist map filter selection through QTMs

### ISSUE THREAD

**Issue by timoschwarzer** [ori-rando/wotw-client#272] opened 2022-02-28 11:03 UTC
Currently, when you set the filter to "In Logic" and QTM, the filter will be reset to "All". There may exist more occurrences of resetting the filter to "All" in the game.

**Comment by MunWolf** [comment] 2022-04-08 06:50
Apparently https://github.com/ori-rando/wotw-client/issues/287 was a duplicate of this one oriLol
but its fixed now

**Closed by MunWolf** 2022-04-08 06:50 UTC
Labels: enhancement
